export const IS_LOCALHOST_ANALYTICS_DISABLED = true;
export const IS_DEFAULT_PROVIDER_DISABLED = false;
export const IS_PROFILE_INVITING_DISABLED = true;
export const IS_NOT_MAIN_JURISDICTION_CASE_JUDGING_DISABLED = true;
